# Generated by Django 3.2 on 2023-03-14 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MedicinesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_no', models.CharField(max_length=150)),
                ('code', models.CharField(max_length=150)),
                ('inn', models.CharField(db_index=True, max_length=150)),
                ('bn', models.CharField(db_index=True, max_length=150)),
                ('form', models.CharField(db_index=True, max_length=150)),
                ('dosing', models.CharField(max_length=150, null=True)),
                ('cond', models.CharField(max_length=150, null=True)),
                ('list', models.CharField(max_length=150, null=True)),
                ('p1', models.CharField(max_length=150, null=True)),
                ('p2', models.CharField(max_length=150, null=True)),
                ('obs', models.CharField(max_length=150, null=True)),
                ('laboratories', models.CharField(db_index=True, max_length=150)),
                ('country', models.CharField(db_index=True, max_length=80)),
            ],
        ),
    ]
