# Generated by Django 3.2 on 2023-03-17 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicinesmodel',
            name='list',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='medicinesmodel',
            name='obs',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='medicinesmodel',
            name='p1',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='medicinesmodel',
            name='p2',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
