# Generated by Django 3.2 on 2023-03-17 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20230317_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicinesmodel',
            name='bn',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='medicinesmodel',
            name='country',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='medicinesmodel',
            name='form',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='medicinesmodel',
            name='inn',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='medicinesmodel',
            name='laboratories',
            field=models.CharField(max_length=150),
        ),
    ]
